### ISSUE TITLE
Sponsored Job Campaigns API Deprecated ?

### ISSUE THREAD

**Issue by daannijkamp** [indeedeng/sponsored-jobs-nodejs-auth-code#1]
Hi,

Is the Sponsored Job Campaigns API Deprecated ?
It seems that the documentation/Swagger API Reference has been removed from the website.  

cc: @swalther-indeed

**Comment by swalther-indeed** [comment]
Hi daannijkamp,

Please reach out to the marketplacesupport@indeed.com email address for questions about access to Indeed APIs.

**Comment by daannijkamp** [comment]
Hi @swalther-indeed,

I've already tried this (multiple times), but I'm not getting any response.
